stages:
    - deploy
  
deploy-sgremote:
  stage: deploy
  image: alphine
  before_script:
  - 'which ssh-agent || ( apk update && apk add --no-cache openssh-client )'
  - eval "$(ssh-agent -s)"
  - echo "$SSH_PRIVATE_KEY_MYMACBOOK" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  script:
    - >
      ssh ~/.ssh/id_rsa -o StrictHostKeyChecking=no sgara@$SGREMOTE_HOST "
      cd /var/www/Project-TPEC-2/ ;
      pwd ;
      "